acsoo/templates/project/+project.name+/.gitlab-ci.yml.bob
The --no-deps won't check missing dependencies and won't break if there are missing dependencies
By keeping the --no-index only we are sure to detect missing dependencies
From https://github.com/acsone/acsoo/pull/29#pullrequestreview-103926641
=> [REF] GitLab CI template: detect missing dependencies

acsoo/cfg/flake8.cfg
W503 has been replaced by W504 in latest flake8. To avoid a lot of changes in our existing projects, allows both
cc @sbidoul @acsone/acsone-odoo-team
=> [FIX] Allow W503 and W504

CHANGES.rst, acsoo/cfg/pylint.cfg
In pylint-odoo 2.0.1 the paramter 'manifest_required_author' has been renamed into 'manifest_required_authors'.
Both parameters are now provided into the default config to be compatible with pytlint-odoo < 2.0.1 and 2.0.1
=> [FIX] acsoo pylint: Compatible with pylint-odoo 2.0.1

.isort.cfg, .pre-commit-config.yaml, acsoo/pylintcmd.py
This fixes the `TypeError: __init__() got an unexpected keyword argument 'exit'` error.
It breaks from this [commit](https://github.com/PyCQA/pylint/commit/4210ef9b8c5d9e7b33ff0542683f18b8031193fa#diff-ade2cfcf3e840a993dbd465f517d91f5L1189) on PyLint.
This solution is taken from [pylint-odoo](https://github.com/OCA/pylint-odoo/commit/5b0f7f9783e607217ec5d7833e15e7dda28122c1#diff-6177c602688f2a88312483059f6523d2R127).
=> [FIX] Acsoo PyLint: python3 compatibility

README.rst, acsoo/templates/project/+project.name+/.gitlab-ci.yml.bob, acsoo/templates/project/+project.name+/.pre-commit-config.yaml, acsoo/templates/project/+project.name+/.pylintrc.bob
- configure using regular pylint config
- provide a default config in project template
- use pre-commit to run pylint (with all associated benefits)
- deprecate acsoo flake8 too (it was already deprecated in the project template)
Main benefits are
- pre-commit allows for earlier detection of issues (at commit time)
- local configuration allows easy integration of pylint in IDE
- one less dependency on acsoo so you learn standard tools, not proprietary stuff
@acsone/acsone-odoo-team
=> deprecate acsoo pylint

acsoo/templates/project/+project.name+/odoo/addons/+project.trigram+_all/__init__.py, acsoo/templates/project/+project.name+/odoo/addons/+project.trigram+_all/__manifest__.py.bob, acsoo/templates/project/+project.name+/odoo/addons/server_environment_files/__manifest__.py.bob
Match pylint-odoo C8202 check.
=> [FIX] Project Template: remote utf-8 header in python file unnecessary

CHANGES.rst, acsoo/templates/project/+project.name+/.gitlab/merge_request_templates/Review.md, acsoo/templates/project/+project.name+/.gitlab/merge_request_templates/WIP.md
This PR adds two examples of [GitLab merge request templates](https://docs.gitlab.com/ee/user/project/description_templates.html#creating-merge-request-templates).
When creating a merge request, a template can be selected, filling the description field. [GitLab Quick Actions](https://docs.gitlab.com/ee/user/project/quick_actions.html) are used to automatically fill some fields (labels, milestone, target branch, assignee) at save.
Used variables such as labels, milestones, branches and users must exist in the project or won't be applied.
The _Review_ template could be improved at the project level with `/assign @{user_name}` to automatically assign the MR to the reviewer.
The _WIP_ template toggles the [WIP mode](https://docs.gitlab.com/ee/user/project/merge_requests/work_in_progress_merge_ …
=> [ADD] Project Template: merge request templates

acsoo/templates/project/+project.name+/.flake8
Align Black and Flake8 configuration by setting the maximum line length to 80 characters to avoid B950 (line too long) error.
https://github.com/psf/black#line-length
=> [IMP] Project Template: set flake8 max. line length to 80

.isort.cfg, .travis.yml, acsoo/__init__.py, acsoo/pr_status.py, setup.cfg, test-requirements.txt, tests/test_pr_status.py, tox.ini
This is a step towards not needing to use gitaggregate for the most common case where we install an addon from a PR.
It gets the PR references (of the form `@refs/pull/NNN/head`) from a python requirements file.
The next step will be to make `acsoo tag-requirements` capable of automatically pushing the PR to the acsone organization where it can tag it.
=> [ADD] acsoo pr-status

acsoo/templates/project/+project.name+/.gitlab-ci.yml.bob
This makepot shouldn't change anything to tests and shouldn't use resources of gitlab-ci.
It's already added in some projects.
=> [IMP] Add the Skip CI into push option of makepot script.

acsoo/templates/project/+project.name+/.gitlab-ci.yml.bob, acsoo/templates/project/+project.name+/.pre-commit-config.yaml, acsoo/templates/project/+project.name+/README.rst.bob, acsoo/templates/project/+project.name+/freeze.bob, acsoo/templates/project/+project.name+/requirements.txt.in.bob, acsoo/templates/project/+project.name+/setup.py.bob
Mostly:
- recommend pip-deepfreeze in README
- modernize pre-commit config
=> Various improvements to project template

.flake8, acsoo/templates/project/+project.name+/.gitlab-ci.yml.bob, acsoo/templates/project/+project.name+/.pre-commit-config.yaml, acsoo/templates/project/+project.name+/README.rst.bob, acsoo/templates/project/+project.name+/deploy-test.bob, acsoo/templates/project/+project.name+/odoo/addons/+project.trigram+_all/__manifest__.py.bob, acsoo/templates/project/+project.name+/odoo/addons/server_environment_files/test/test.conf, acsoo/templates/project/+project.name+/requirements-find-links.txt.bob, acsoo/templates/project/+project.name+/setup.py.bob, tests/test_pr_status.py
See individual commits.
cc/ @acsone/acsone-odoo-team
=> Project template: various improvements

acsoo/tag.py
git ls-files with the --directory option returns the path to empty directories
This is not a case of having an unclean working directory.
=> [IMP] do not raise if only empty folders in working tree

CHANGES.rst, README.rst, acsoo/templates/project/+project.name+/.gitlab-ci.yml.bob
[Manifestoo](https://pypi.org/project/manifestoo/) is an evolution of `acsoo addons` with better test coverage and more features.
In particular, it provides a `check-licenses` command to help ensure we don't mix proprietary and xGPL code.
Similarly, `check-dev-status` helps avoiding the use of Alpha-level OCA modules.
Also, use our latest odoo ci image which has pipx pre-installed, simplifying installation of python tools such as acsoo itself (which we still need in CI for the `checklog` command).
=> License check, and deprecate acsoo addons in favor of manifestoo

CHANGES.rst, README.rst, setup.cfg
This project is now replaced by bump2versions, and it's better to install it separately with pipx.
=> Remove bumpversion from acsoo dependencies

setup.cfg
As the version 1.7 of lazy-object-proxy does not provide support for python2.7, we should use the previous one.
=> lazy-object-proxy version restriction for python2

acsoo/config.py, acsoo/templates/project/.mrbob.ini
Add possibility to use `acsoo` with Odoo `16.0`.
For now I only test this command who works perfectly:
`acsoo tag-requirements`
I did a secondary commit about a little improvement, to generate automatically supported Odoo versions.
=> [ADD] Support Odoo 16

acsoo/templates/project/+project.name+/.eslintrc.yml
The previous eslinrtc configuration file wasn't working with odoo 16, because the sourceType key was missing. 
Upgrade ecmaVersion to 2019 adds new tokens that are used in odoo JS.
=> [IMP] Project Template - Use a newer configuration for eslintrc

README.rst
We deprecate acsoo tag and tag-requirements.
A better replacement is to configure `pip-preserve-requirements requirements*.txt` as a pip-deepfreeze post_sync_command in your [pyproject.toml](https://github.com/sbidoul/pip-deepfreeze#configuration).
=> Deprecate acsoo tag and acsoo tag-requirements

acsoo/pr_status.py
The organization name and the repository can contain digits.
E.g. https://github.com/OCA/l10n-belgium
=> [FIX] pr_status: manage PR URL's containing numerical characters
